# Generated by Django 6.0.4 on 2026-04-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("OTP_REQUESTED", "OTP Requested"),
                            ("OTP_VERIFIED", "OTP Verified"),
                            ("OTP_FAILED", "OTP Failed"),
                            ("OTP_LOCKED", "OTP Locked"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(
                    auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "event"], name="audit_email_event_idx"
                    ),
                    models.Index(fields=["created_at"],
                                 name="audit_created_at_idx"),
                ],
            },
        ),
    ]
